version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /netseq.wdl
     testParameterFiles:
         - /test/inputs.json
   - subclass: WDL
     primaryDescriptorPath: /chcker_netseq.wdl
     testParameterFiles:
         - /test/checker_inputs.json
